### ISSUE TITLE
Breaks with dependency stampit 2.*

### ISSUE THREAD

**Issue by blub0hr** [koresar/fcql#2]
The `package.json` defines `stampit >= 0.6.1` as dependency but `fcql` only works with `stampit 1.*`. Current stable stampit version is at `2.*` tho, so that is being installed.

**Comment by koresar** [comment]
Few months later I found this issue. Sorry not responding. The notifications were Off for some reason. :\

PRs are welcome any time. :)

**Comment by koresar** [comment]
Thanks for reporting the issue. I got it fixed. Stampit v1 is used now. the module was published as `fcql@0.1.1`

Cheers.
